In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame
ratings = pd.read_csv(r'user_reviews.csv')

In [2]:
ratings = ratings.drop(["Unnamed: 0"], axis = 1).set_index(["User"]).astype(int)
#ratings = ratings.drop(ratings.index[200:500],axis=0)

In [3]:
#The following commands are to shrink the original data set
#delete the users with least ratings on the movies
#duser = ratings.sum(axis=1).sort_values(ascending=True)[:550].index.values.tolist()

#delete the users from the bottom of the list
ratings = ratings.drop(ratings.index[300:],axis=0)

#delete movies with least ratings from the users
ditem = ratings.sum(axis=0).sort_values(ascending=True)[:1000].index.values.tolist()
ratings = ratings.drop(ditem, axis = 1)#.drop(duser, axis = 0)
ratings

,The Net,Tomorrowland,American Hero,Das Boot,Final Destination 3,Licence to Kill,The Hundred-Foot Journey,Creature,The Basket,The Hunger Games,...,Mrs Henderson Presents,Archaeology of a Woman,Force 10 from Navarone,Animal Kingdom,The Brain That Sings,Micmacs,Solomon and Sheba,Silent House,Big Fish,Hey Arnold! The Movie
User,,,,,,,,,,,,,,,,,,,,,
Vincent,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Edgar,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Addilyn,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Marlee,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Javier,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Royalty,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Kyrie,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Audrey,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Elise,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Andy,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [4]:
mcors = np.corrcoef(ratings, rowvar=1)
mcors = mcors*0.5+0.5
mcors = pd.DataFrame(mcors, columns=ratings.index, index=ratings.index)
mcors

User,Vincent,Edgar,Addilyn,Marlee,Javier,Marcus,Mary,Rosalie,Giovanni,Kennedi,...,Graham,Elena,Anderson,Alivia,Jonas,Royalty,Kyrie,Audrey,Elise,Andy
User,,,,,,,,,,,,,,,,,,,,,
Vincent,1.000000,0.500704,0.503400,0.489026,0.490573,0.491468,0.492228,0.489457,0.490222,0.527275,...,0.489511,0.520698,0.491222,0.490753,0.488359,0.505262,0.520583,0.490323,0.493111,0.487262
Edgar,0.500704,1.000000,0.488275,0.489011,0.511307,0.491457,0.492217,0.489443,0.490208,0.528099,...,0.489497,0.504490,0.515873,0.490741,0.495157,0.489093,0.491524,0.490309,0.493102,0.554993
Addilyn,0.503400,0.488275,1.000000,0.516691,0.490036,0.490982,0.517061,0.488857,0.489665,0.491038,...,0.488914,0.498248,0.490722,0.523356,0.487696,0.542740,0.519606,0.520767,0.555489,0.514585
Marlee,0.489026,0.489011,0.516691,1.000000,0.513438,0.491549,0.492301,0.489557,0.490314,0.491601,...,0.537311,0.488976,0.491304,0.528705,0.488468,0.514921,0.491616,0.490414,0.493176,0.522004
Javier,0.490573,0.511307,0.490036,0.513438,1.000000,0.492740,0.493387,0.491029,0.491680,0.492785,...,0.491075,0.515716,0.532262,0.492132,0.490094,0.490732,0.492798,0.491765,0.494138,0.489161
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Royalty,0.505262,0.489093,0.542740,0.514921,0.490732,0.491612,0.492359,0.489635,0.510786,0.529239,...,0.500844,0.489059,0.491370,0.526330,0.505349,1.000000,0.491678,0.515340,0.493227,0.505470
Kyrie,0.520583,0.491524,0.519606,0.491616,0.492798,0.493481,0.494062,0.491945,0.548774,0.493522,...,0.491986,0.491497,0.493293,0.492935,0.491106,0.491678,1.000000,0.492606,0.494737,0.490268
Audrey,0.490323,0.490309,0.520767,0.490414,0.491765,0.492547,0.501124,0.490791,0.491459,0.492593,...,0.490838,0.490278,0.502220,0.491923,0.504583,0.515340,0.492606,1.000000,0.493982,0.488873
Elise,0.493111,0.493102,0.555489,0.493176,0.494138,0.494695,0.495167,0.493444,0.493920,0.494727,...,0.493478,0.493079,0.506556,0.494250,0.492761,0.493227,0.494737,0.493982,1.000000,0.492079
Andy,0.487262,0.554993,0.514585,0.522004,0.489161,0.507708,0.491064,0.487878,0.488757,0.490251,...,0.502128,0.487204,0.498855,0.489368,0.486615,0.505470,0.490268,0.488873,0.492079,1.000000

In [5]:
def cal_score(matrix,mcors,item,user):
    totscore = 0
    totsims = 0
    score = 0
    if matrix[item][user]==0:
        for muser in ratings.index:
            if matrix[item][muser]==0:
                continue
            if pd.isnull(mcors[user][muser]):
                continue
            else:
                totscore += matrix[item][muser]*mcors[user][muser]
                #totsims += mcors[user][muser]
                totsims = totsims + 1
        if totsims == 0:
            score = matrix[item][user]
        else:
            score = totscore/totsims
    else:
        score = matrix[item][user]
    return score

In [6]:
def cal_matscore(matrix,mcors):
    score_matrix = np.zeros(matrix.shape)
    score_matrix = pd.DataFrame(score_matrix, columns=matrix.columns, index=matrix.index)
    for mitem in matrix.columns:
        for muser in matrix.index:
            score_matrix[mitem][muser] = cal_score(matrix,mcors,mitem,muser)
    return score_matrix

In [7]:
def recommend(matrix,score_matrix,user,n):
    user_ratings= matrix.loc[user]
    not_rated_item = user_ratings[user_ratings==0]
    recom_items = {}
    for item in not_rated_item.index:
        recom_items[item]=score_matrix[item][user]
    recom_items = pd.Series(recom_items)
    recom_items = recom_items.sort_values(ascending=False)
    return recom_items[:n]

In [8]:
score_matrix = cal_matscore(ratings,mcors)

In [10]:
for i in range(5):
    user = input(str(i)+" please input the user name:")
    print(recommend(ratings,score_matrix,user,5))

0 please input the user name:Vincent
Blue Like Jazz                2.584528
The Object of My Affection    2.532498
The Tempest                   2.524778
Beautiful Creatures           2.518211
Spotlight                     2.509707
dtype: float64
1 please input the user name:Edgar
How Do You Know                        2.554467
Spotlight                              2.551390
Mad City                               2.520728
Beautiful Creatures                    2.509826
The Curious Case of Benjamin Button    2.489338
dtype: float64
2 please input the user name:Addilyn
Evolution                                    2.534008
Beautiful Creatures                          2.523871
How Do You Know                              2.523637
Seeking a Friend for the End of the World    2.488932
The Curious Case of Benjamin Button          2.482356
dtype: float64
3 please input the user name:Marlee
Mad City           2.573293
Spotlight          2.562815
Blue Like Jazz     2.528703
How Do You Know    2.516456
Evolution          2.486101
dtype: float64
4 please input the user name:Javier
Evolution                              2.560685
A Scanner Darkly                       2.539782
Spotlight                              2.526091
The Curious Case of Benjamin Button    2.515112
The Tempest                            2.500496
dtype: float64

In [9]:
score_matrix

,The Net,Tomorrowland,American Hero,Das Boot,Final Destination 3,Licence to Kill,The Hundred-Foot Journey,Creature,The Basket,The Hunger Games,...,Mrs Henderson Presents,Archaeology of a Woman,Force 10 from Navarone,Animal Kingdom,The Brain That Sings,Micmacs,Solomon and Sheba,Silent House,Big Fish,Hey Arnold! The Movie
User,,,,,,,,,,,,,,,,,,,,,
Vincent,2.034704,1.793598,2.312538,2.200022,1.257096,1.629061,2.478926,1.585877,1.388038,1.616757,...,1.820900,1.555618,1.895564,2.160566,1.846613,1.553962,2.343021,2.160131,1.717037,2.011728
Edgar,2.089230,1.790885,2.332768,2.167512,1.250187,1.641891,2.448130,1.598499,1.423113,1.622717,...,1.812824,1.544179,1.907913,2.125783,1.846574,1.562743,2.286543,2.225494,1.693726,2.041419
Addilyn,2.048806,1.785778,2.302932,2.226992,1.234268,1.663916,2.464937,1.561281,1.368543,1.633676,...,1.817802,1.543533,1.911800,2.169027,1.844997,1.562602,2.328308,2.157634,1.717811,2.016303
Marlee,2.053068,1.765591,2.319527,2.245452,1.252974,1.641367,2.448689,1.565952,1.421904,1.629658,...,1.805964,1.569893,1.910727,2.126224,1.846881,1.594217,2.319520,2.151666,1.698731,1.986914
Javier,2.051187,1.831172,2.357783,2.250867,1.250384,1.625143,2.455923,1.581144,1.399926,1.623897,...,1.800359,1.527437,1.932228,2.131926,1.863502,1.570649,2.344403,2.166756,1.716216,1.991870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Royalty,2.043119,1.784656,2.282854,2.192669,1.248589,1.658863,2.495378,1.592719,1.378223,1.659651,...,1.841382,1.562425,1.917033,2.335654,1.849049,1.567996,2.355366,2.174903,1.685667,1.981656
Kyrie,2.056221,1.816297,2.405798,2.220665,1.280653,1.632699,2.460424,1.558561,1.412244,1.649135,...,1.836791,1.565890,1.928539,2.135473,1.853312,1.560893,2.297633,2.156303,1.714466,2.015840
Audrey,2.029023,1.770398,2.312351,2.231674,1.265485,1.630556,2.454752,1.555010,1.387833,1.625281,...,1.825464,1.540483,1.914704,2.131002,1.854786,1.594189,2.292516,2.138276,1.711932,2.010236
Elise,2.043779,1.778399,2.372868,2.185240,1.236300,1.678772,2.467789,1.563171,1.381493,1.668252,...,1.809236,1.545115,1.912202,2.182829,1.904110,1.565069,2.304277,2.195869,1.692142,1.972440
Andy,5.000000,1.771536,2.328927,2.175082,1.245894,1.654219,2.467821,1.578470,1.398573,1.628602,...,1.803649,1.535865,1.936010,2.119723,1.848472,1.565998,2.279607,2.163226,1.687845,1.000000